message = "This is your secret message, stored in .streamlit/secrets.toml. Remember to add it to .gitignore!"

[non_environment]
message = "This secret is not exported into an environmental variable."
